BeforeAll {
    $script:RepoRoot = Split-Path $PSScriptRoot -Parent
    $script:ModulePath = Join-Path $script:RepoRoot 'src\module\AgExpert.Launcher\AgExpert.Launcher.psd1'
    Get-Module AgExpert.Launcher | Remove-Module -Force -ErrorAction SilentlyContinue
    Import-Module $script:ModulePath -Force

    $script:Registry = (Get-Content (Join-Path $script:RepoRoot 'config\apis.json') -Raw | ConvertFrom-Json).apis
}

Describe 'API registry' {
    It 'defines unique product names' {
        $duplicates = $script:Registry | Group-Object { $_.name.ToLowerInvariant() } | Where-Object Count -gt 1
        $duplicates | Should -BeNullOrEmpty
    }

    It 'defines unique ports' {
        $duplicates = $script:Registry | Group-Object port | Where-Object Count -gt 1
        $duplicates | Should -BeNullOrEmpty
    }

    It 'gives every entry a proxy display name' {
        $script:Registry | Where-Object { -not $_.proxyName } | Should -BeNullOrEmpty
    }

    It 'gives every runnable entry a directory and default profile' {
        $incomplete = $script:Registry | Where-Object { -not $_.proxyOnly -and (-not $_.directory -or -not $_.defaultProfile) }
        $incomplete | Should -BeNullOrEmpty
    }

    It 'omits the directory for proxy-only entries' {
        $script:Registry | Where-Object { $_.proxyOnly -and $_.directory } | Should -BeNullOrEmpty
    }

    It 'uses forward slashes in directories' {
        $script:Registry | Where-Object { $_.directory -and $_.directory -match '\\' } | Should -BeNullOrEmpty
    }
}

Describe 'Registry parity with the extension' {
    It 'ships the same registry file to the extension at package time' {
        $extensionConfig = Join-Path $script:RepoRoot 'src\extension\config\apis.json'
        if (-not (Test-Path $extensionConfig)) {
            Set-ItResult -Skipped -Because 'the extension config is generated by Build-AgExpertRelease.ps1'
            return
        }

        $shipped = (Get-Content $extensionConfig -Raw | ConvertFrom-Json).apis
        ($shipped | Select-Object -ExpandProperty name | Sort-Object) -join ',' |
            Should -Be (($script:Registry | Select-Object -ExpandProperty name | Sort-Object) -join ',')
    }

    It 'reads the same entries through the module' {
        (Get-AgExpertApiConfig).Count | Should -Be $script:Registry.Count
    }
}

Describe 'Name resolution' {
    It 'resolves <Name> to port <Port>' -ForEach @(
        @{ Name = 'field'; Port = 44315 }
        @{ Name = 'fieldApi'; Port = 44315 }
        @{ Name = 'Field API'; Port = 44315 }
        @{ Name = '44315'; Port = 44315 }
        @{ Name = 'mcCain'; Port = 44332 }
        @{ Name = 'climateFieldView'; Port = 44331 }
    ) {
        (Resolve-AgExpertProxyService $Name).Port | Should -Be $Port
    }

    It 'resolves every registered product name' {
        foreach ($entry in $script:Registry) {
            (Resolve-AgExpertProxyService $entry.name).Port | Should -Be $entry.port
        }
    }

    It 'rejects an unknown service' {
        { Resolve-AgExpertProxyService 'nonexistent' } | Should -Throw '*Unknown proxy service*'
    }
}

Describe 'FMPro repository layout' -Tag 'Integration' {
    BeforeAll {
        $script:FmProRoot = (Get-Content (Join-Path $script:RepoRoot 'config\settings.default.json') -Raw |
                ConvertFrom-Json).repoRoot -replace '/', '\'
    }

    It 'has a project directory for every runnable API' {
        if (-not (Test-Path $script:FmProRoot)) {
            Set-ItResult -Skipped -Because 'the FMPro repository is not present'
            return
        }

        $missing = foreach ($entry in $script:Registry | Where-Object { -not $_.proxyOnly }) {
            $path = Join-Path $script:FmProRoot ($entry.directory -replace '/', '\')
            if (-not (Test-Path $path)) { $entry.name }
        }
        $missing | Should -BeNullOrEmpty
    }

    It 'has the default launch profile for every runnable API' {
        if (-not (Test-Path $script:FmProRoot)) {
            Set-ItResult -Skipped -Because 'the FMPro repository is not present'
            return
        }

        $missing = foreach ($entry in $script:Registry | Where-Object { -not $_.proxyOnly }) {
            $launchSettings = Join-Path $script:FmProRoot (($entry.directory -replace '/', '\') + '\Properties\launchSettings.json')
            if (-not (Test-Path $launchSettings)) { "$($entry.name): no launchSettings.json"; continue }

            $profileNames = (Get-Content $launchSettings -Raw | ConvertFrom-Json).profiles.PSObject.Properties.Name
            if ($profileNames -notcontains $entry.defaultProfile) { "$($entry.name): no '$($entry.defaultProfile)' profile" }
        }
        $missing | Should -BeNullOrEmpty
    }
}
